### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by stephen-farris-jhuapl-edu** [willymcallister/circuit-sandbox#37]
What is the license for this code? Are the restrictions on modifying it?

**Comment by willymcallister** [comment]
https://spinningnumbers.org/a/circuit-sandbox.html#licensing

This work is licensed under the Creative Commons (CC BY-NC-SA 4.0) Attribution-NonCommercial-ShareAlike 4.0 International.

Khan Academy makes its software available under the MIT License.

The MIT circuit simulator is part of the EdX Platform, licensed under the GNU AFFERO GENERAL PUBLIC LICENSE Version 3, 19 November 2007. More information at EdX licensing.

There are no restrictions on modifying the Circuit Sandbox code, other than the attribution request described in these licenses. I would be delighted if you shared your modifications with me.

**Comment by stephen-farris-jhuapl-edu** [comment]
thank you!
